# Generated by Django 4.2.11 on 2025-04-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
